
version: "3"

services:
  reverse-proxy:
    image: "traefik:v2.0.0"
    container_name: "traefik"
    command:
      - "--log.level=INFO"
      - "--api.dashboard=true"
      - "--api"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.traefik.address=:8080"
      - "--certificatesresolvers.certchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.certchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.certchallenge.acme.email=notifyme@paref.edu.ph"
      - "--certificatesresolvers.certchallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - letsencrypt:/letsencrypt
    networks:
      - frontend

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webserver
    volumes:
      - ./website:/var/www/html
    networks:
      - frontend
    restart: on-failure
    labels:
     - "traefik.http.routers.web.rule=Host(`XXXX-XXXX-XXXX-XXXX`)"
     - "traefik.http.routers.web.entrypoints=websecure"
     - "traefik.http.routers.web.service=web"
     - "traefik.http.services.web.loadbalancer.server.port=80"
     - "traefik.http.routers.web.tls.certresolver=certchallenge"
     - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
     - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
     - "traefik.http.routers.redirs.entrypoints=web"
     - "traefik.http.routers.redirs.middlewares=redirect-to-https"
  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    networks:
      - frontend
    restart: on-failure
    volumes:
     - mysql-data:/var/lib/mysql


  phpmyadmin:
    container_name: phpmyadmin

    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE}
      PMA_ABSOLUTE_URI: "https://XXXX-XXXX-XXXX-XXXX/phpmyadmin/"

    networks:
      - frontend
    labels:
      - traefik.enable=true
      - "traefik.http.routers.phpmyadmin.rule=Host(`registrar.img.parefwestbridge.edu.ph`) && (PathPrefix(`/phpmyadmin`))"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=certchallenge"
      - "traefik.http.routers.phpmyadmin.middlewares=phpmyadmin-strip"
      - "traefik.http.middlewares.phpmyadmin-strip.stripprefix.prefixes=/phpmyadmin"

volumes:
  mysql-data: {}
  letsencrypt: {}

networks:
  frontend:
    external: true
